/var/log/inforsight/traffic.log {
    size 1M
    rotate 30
    missingok
    notifempty
    nocompress
    create 0644 root root
    postrotate
        if [ -f /var/run/nginx.pid ]; then kill -USR1 "$(cat /var/run/nginx.pid)"; fi
    endscript
}
