apiVersion: v1
kind: Service
metadata:
  name: {{ include "inforsight.fullname" . }}-control-plane
  labels:
    {{- include "inforsight.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports: [{ name: http, port: {{ .Values.controlPlane.port }}, targetPort: http }]
