"""Inforsight's clean-room fictional policy-event simulator."""

from .config import GeneratorConfig
from .generator import generate_policy_histories, generation_provenance
from .features import (
    FEATURE_DEFINITIONS,
    FEATURE_DICTIONARY_VERSION,
    FEATURE_PIPELINE_VERSION,
    ExtractedFeatureRow,
    FeatureDefinition,
    extract_feature_row,
    feature_dictionary,
    validate_feature_dictionary,
)
from .leakage import (
    FEATURE_GUARD_VERSION,
    find_exact_deterministic_proxies,
    validate_feature_payload,
    validate_observation_records,
)
from .observations import (
    LABEL_HORIZON_DAYS,
    LABEL_POLICY_VERSION,
    OBSERVATION_CONTRACT_VERSION,
    ObservationFeatures,
    ObservationRecord,
    OutcomeLabel,
    build_first_billing_observations,
    build_observation,
    first_billing_observation_time,
    summarize_observations,
)
from .modeling import (
    BASELINE_RANDOM_SEED,
    FROZEN_LOGISTIC_SPECIFICATION,
    LOGISTIC_BASELINE_VERSION,
    TRAINING_CONFIGURATION_VERSION,
    BaselineEvaluation,
    BaselineMetrics,
    FittedLogisticBaseline,
    LogisticBaselineSpecification,
    coefficient_summary,
    evaluate_logistic_baseline,
    fit_logistic_baseline,
    fitted_baseline_bytes,
    predict_positive_probabilities,
)
from .boosted_modeling import (
    BOOSTED_MODEL_VERSION,
    BOOSTED_RANDOM_SEED,
    BOOSTED_TRAINING_CONFIGURATION_VERSION,
    FROZEN_BOOSTED_SPECIFICATION,
    XGBOOST_PINNED_VERSION,
    BoostedModelSpecification,
    FittedBoostedModel,
    compare_models,
    evaluate_boosted_model,
    fit_boosted_model,
    fitted_boosted_bytes,
    predict_boosted_probabilities,
)
from .diagnostics import (
    DIAGNOSTIC_CONFIGURATION_VERSION,
    DIAGNOSTIC_RANDOM_SEED,
    FEATURE_DIAGNOSTICS_VERSION,
    FROZEN_DIAGNOSTIC_SPECIFICATION,
    DiagnosticSpecification,
    diagnostic_flags,
    identifier_and_cardinality_checks,
    identifier_token_matches,
    perturbation_flags,
    shallow_feature_models,
    source_feature_groups,
    targeted_permutation_checks,
    training_mutual_information,
    validate_dispositions,
)
from .reconstruction import PolicyState, reconstruct_policy_state
from .preprocessing import (
    UNKNOWN_CATEGORY,
    FeaturePipelineResult,
    FittedPreprocessor,
    ModelMatrix,
    build_feature_pipeline,
    fit_preprocessor,
    fitted_state_bytes,
    matrix_digest,
    transform_partition,
)
from .serialization import histories_to_jsonl
from .splitting import (
    CANONICAL_TEMPORAL_SPLIT_SPECIFICATION,
    TEMPORAL_SPLIT_CONTRACT_VERSION,
    TemporalSplitResult,
    TemporalSplitSpecification,
    assign_temporal_splits,
    source_observation_digest,
    summarize_temporal_split,
    validate_temporal_split,
)
from .validation import validate_policy_history


__version__ = "0.1.0"

__all__ = [
    "GeneratorConfig",
    "BASELINE_RANDOM_SEED",
    "BOOSTED_MODEL_VERSION",
    "BOOSTED_RANDOM_SEED",
    "BOOSTED_TRAINING_CONFIGURATION_VERSION",
    "FROZEN_BOOSTED_SPECIFICATION",
    "FROZEN_LOGISTIC_SPECIFICATION",
    "FROZEN_DIAGNOSTIC_SPECIFICATION",
    "LOGISTIC_BASELINE_VERSION",
    "TRAINING_CONFIGURATION_VERSION",
    "FEATURE_DEFINITIONS",
    "FEATURE_DICTIONARY_VERSION",
    "FEATURE_GUARD_VERSION",
    "FEATURE_PIPELINE_VERSION",
    "FEATURE_DIAGNOSTICS_VERSION",
    "DIAGNOSTIC_CONFIGURATION_VERSION",
    "DIAGNOSTIC_RANDOM_SEED",
    "LABEL_HORIZON_DAYS",
    "LABEL_POLICY_VERSION",
    "OBSERVATION_CONTRACT_VERSION",
    "CANONICAL_TEMPORAL_SPLIT_SPECIFICATION",
    "TEMPORAL_SPLIT_CONTRACT_VERSION",
    "ObservationFeatures",
    "ObservationRecord",
    "OutcomeLabel",
    "ExtractedFeatureRow",
    "FeatureDefinition",
    "FeaturePipelineResult",
    "FittedPreprocessor",
    "ModelMatrix",
    "BaselineEvaluation",
    "BaselineMetrics",
    "FittedLogisticBaseline",
    "LogisticBaselineSpecification",
    "BoostedModelSpecification",
    "FittedBoostedModel",
    "DiagnosticSpecification",
    "TemporalSplitResult",
    "TemporalSplitSpecification",
    "UNKNOWN_CATEGORY",
    "assign_temporal_splits",
    "build_first_billing_observations",
    "build_feature_pipeline",
    "build_observation",
    "coefficient_summary",
    "compare_models",
    "diagnostic_flags",
    "evaluate_boosted_model",
    "evaluate_logistic_baseline",
    "first_billing_observation_time",
    "fit_preprocessor",
    "fit_logistic_baseline",
    "fit_boosted_model",
    "fitted_boosted_bytes",
    "fitted_baseline_bytes",
    "fitted_state_bytes",
    "identifier_and_cardinality_checks",
    "identifier_token_matches",
    "find_exact_deterministic_proxies",
    "generate_policy_histories",
    "generation_provenance",
    "extract_feature_row",
    "feature_dictionary",
    "histories_to_jsonl",
    "PolicyState",
    "project_identity",
    "reconstruct_policy_state",
    "source_observation_digest",
    "matrix_digest",
    "predict_positive_probabilities",
    "predict_boosted_probabilities",
    "perturbation_flags",
    "shallow_feature_models",
    "source_feature_groups",
    "targeted_permutation_checks",
    "training_mutual_information",
    "summarize_observations",
    "summarize_temporal_split",
    "validate_feature_payload",
    "validate_feature_dictionary",
    "validate_observation_records",
    "validate_policy_history",
    "validate_temporal_split",
    "validate_dispositions",
    "transform_partition",
    "XGBOOST_PINNED_VERSION",
]


def project_identity() -> dict[str, str]:
    """Return public project metadata used by the scaffold smoke test."""
    return {
        "name": "Inforsight",
        "tagline": "See Risk. Shape Action.",
        "data_policy": "synthetic-only",
    }
