"""Inforsight's clean-room fictional policy-event simulator."""

from .config import GeneratorConfig
from .generator import (
    CONFIGURATION_CANONICALIZATION_VERSION,
    CONFIGURATION_DIGEST_ALGORITHM,
    LEGACY_GENERATOR_VERSION,
    NAMESPACED_GENERATOR_VERSION,
    canonical_configuration,
    configuration_digest,
    generate_legacy_policy_histories,
    generate_policy_histories,
    generation_provenance,
    legacy_generation_provenance,
    run_identity,
    verify_generation_provenance,
)
from .features import (
    FEATURE_DEFINITIONS,
    FEATURE_DICTIONARY_VERSION,
    FEATURE_PIPELINE_VERSION,
    ExtractedFeatureRow,
    FeatureDefinition,
    extract_feature_row,
    feature_dictionary,
    validate_feature_dictionary,
)
from .leakage import (
    FEATURE_GUARD_VERSION,
    find_exact_deterministic_proxies,
    validate_feature_payload,
    validate_observation_records,
)
from .observations import (
    LABEL_HORIZON_DAYS,
    LABEL_POLICY_VERSION,
    OBSERVATION_CONTRACT_VERSION,
    ObservationFeatures,
    ObservationRecord,
    OutcomeLabel,
    build_first_billing_observations,
    build_observation,
    first_billing_observation_time,
    summarize_observations,
)
from .modeling import (
    BASELINE_RANDOM_SEED,
    FROZEN_LOGISTIC_SPECIFICATION,
    LOGISTIC_BASELINE_VERSION,
    TRAINING_CONFIGURATION_VERSION,
    BaselineEvaluation,
    BaselineMetrics,
    FittedLogisticBaseline,
    LogisticBaselineSpecification,
    coefficient_summary,
    evaluate_logistic_baseline,
    fit_logistic_baseline,
    fitted_baseline_bytes,
    predict_logistic_inference,
    predict_positive_probabilities,
)
from .boosted_modeling import (
    BOOSTED_MODEL_VERSION,
    BOOSTED_RANDOM_SEED,
    BOOSTED_TRAINING_CONFIGURATION_VERSION,
    FROZEN_BOOSTED_SPECIFICATION,
    XGBOOST_PINNED_VERSION,
    BoostedModelSpecification,
    FittedBoostedModel,
    compare_models,
    evaluate_boosted_model,
    fit_boosted_model,
    fitted_boosted_bytes,
    predict_boosted_inference,
    predict_boosted_probabilities,
)
from .diagnostics import (
    DIAGNOSTIC_CONFIGURATION_VERSION,
    DIAGNOSTIC_RANDOM_SEED,
    FEATURE_DIAGNOSTICS_VERSION,
    FROZEN_DIAGNOSTIC_SPECIFICATION,
    DiagnosticSpecification,
    diagnostic_flags,
    identifier_and_cardinality_checks,
    identifier_token_matches,
    perturbation_flags,
    shallow_feature_models,
    source_feature_groups,
    targeted_permutation_checks,
    training_mutual_information,
    validate_dispositions,
)
from .reconstruction import PolicyState, reconstruct_policy_state
from .preprocessing import (
    UNKNOWN_CATEGORY,
    FeaturePipelineResult,
    FittedPreprocessor,
    ModelMatrix,
    build_feature_pipeline,
    fit_preprocessor,
    fitted_state_bytes,
    matrix_digest,
    transform_partition,
)
from .scoring_authorization import (
    DIAGNOSTIC_DERIVATIVE,
    HISTORICAL_TRAIN,
    NON_FINAL_VALIDATION,
    SCORING_AUTHORIZATION_VERSION,
    InferenceMatrix,
    ScoringAuthorization,
    ScoringAuthorizations,
    authorize_diagnostic_derivative,
    authorize_feature_pipeline,
    inference_matrix_from_model_matrix,
    validate_scoring_authorization,
)
from .serialization import histories_to_jsonl
from .splitting import (
    CANONICAL_TEMPORAL_SPLIT_SPECIFICATION,
    TEMPORAL_SPLIT_CONTRACT_VERSION,
    TemporalSplitResult,
    TemporalSplitSpecification,
    assign_temporal_splits,
    source_observation_digest,
    summarize_temporal_split,
    validate_temporal_split,
)
from .validation import validate_policy_history
from .v2_config import (
    V2_ACCEPTANCE_PROTOCOL_VERSION,
    V2_CONFIGURATION_CANONICALIZATION_VERSION,
    V2_FINAL_HOLDOUT_STATUS,
    V2_LABEL_POLICY_VERSION,
    V2_OBSERVATION_CONTRACT_VERSION,
    V2_RANDOM_DOMAINS,
    V2_ROLE_PROPORTIONS,
    V2_SIMULATOR_CONTRACT_VERSION,
    V2CorpusConfig,
    canonical_v2_configuration,
    v2_configuration_digest,
    v2_domain_seed,
    v2_run_identity,
)
from .v2_corpus import (
    V2_ARTIFACT_VERSION,
    V2_EVENT_SCHEMA_VERSION,
    V2_ORACLE_SIDECAR_VERSION,
    V2_QUADRATURE_VERSION,
    V2_NUMERIC_SERIALIZATION_DECIMALS,
    V2Corpus,
    V2Features,
    V2Observation,
    V2OracleRecord,
    competing_hazards,
    corpus_jsonl,
    cumulative_incidence,
    generate_v2_corpus,
    observable_oracle,
    validate_v2_corpus,
    validate_v2_feature_payload,
)
from .v3_config import (
    V3_ACCEPTANCE_PROTOCOL_VERSION, V3_CANONICALIZATION_VERSION,
    V3_CONTRACT_VERSION, V3_FINAL_HOLDOUT_STATUS, V3_RANDOM_DOMAINS,
    V3_STREAM_REGISTRY_VERSION, V3CorpusConfig, artifact_id,
    canonical_json_bytes, complete_configuration, execution_id,
    intervention_manifest, primitive_normal, primitive_uniform,
    scenario_configuration, stable_identifier, stream_set_id,
    structural_configuration,
)
from .v3_corpus import (
    V3_ARTIFACT_VERSION, V3_EVENT_SCHEMA_VERSION, V3_OBSERVATION_SCHEMA_VERSION,
    V3_ORACLE_SIDECAR_VERSION, V3_QUADRATURE_VERSION, V3Corpus, V3Features,
    V3Observation, V3OracleRecord, competing_hazards as v3_competing_hazards,
    corpus_digest as v3_corpus_digest, cumulative_incidence as v3_cumulative_incidence,
    generate_v3_corpus, observable_oracle as v3_observable_oracle,
    reconstruct_v3_features, validate_feature_lineage, validate_v3_corpus,
    validate_v3_feature_payload, visible_events,
)
from .v3_1_config import (
    V31_ACCEPTANCE_PROTOCOL_VERSION, V31_SIMULATOR_CONTRACT_VERSION,
    V31CorpusConfig,
)
from .v3_1_corpus import generate_v3_corpus as generate_v31_corpus
from .v4_config import (
    V4_ACCEPTANCE_PROTOCOL_VERSION, V4_COEFFICIENT_REGISTRY_VERSION,
    V4_RANDOM_DOMAINS, V4_SIMULATOR_CONTRACT_VERSION,
    V4_STREAM_REGISTRY_VERSION, V4CorpusConfig,
    artifact_id as v4_artifact_id, complete_configuration as v4_complete_configuration,
    execution_id as v4_execution_id, stream_set_id as v4_stream_set_id,
)
from .v4_corpus import (
    V4_ARTIFACT_VERSION, V4_EVENT_SCHEMA_VERSION, V4_OBSERVATION_SCHEMA_VERSION,
    V4_ORACLE_SIDECAR_VERSION, V4_QUADRATURE_VERSION, V4Corpus, V4Features,
    V4Observation, V4OracleRecord, competing_hazards as v4_competing_hazards,
    corpus_digest as v4_corpus_digest, cumulative_incidence as v4_cumulative_incidence,
    generate_v4_corpus, observable_oracle as v4_observable_oracle,
    public_mechanism_terms, reconstruct_v4_features, validate_v4_corpus,
)
from .v3_evaluation import (
    FEATURE_GROUPS as V3_FEATURE_GROUPS, FOLDS as V3_EVALUATION_FOLDS,
    V3_CANDIDATE_SELECTION_MEMBERSHIP_VERSION, V3_CANDIDATE_VERSION,
    V3_DIAGNOSTIC_VERSION, V3_EVALUATION_ACCEPTANCE_PROTOCOL_VERSION,
    V3_FEATURE_DICTIONARY_VERSION, V3_FEATURE_PIPELINE_VERSION,
    V3_SCORING_AUTHORIZATION_VERSION, V3_SPLIT_VERSION,
    V3_STRUCTURAL_SUPPORT_VERSION, V3Matrix, V3Preprocessor,
    V3ScoringAuthorization, V3TemporalFold,
    authorize as authorize_v3_scoring,
    build_selection_fold as build_v3_selection_fold,
    build_temporal_folds as build_v3_temporal_folds,
    compare_candidates as compare_v3_candidates,
    diagnostics as v3_feature_diagnostics,
    fit_preprocessor as fit_v3_preprocessor,
    matrix_digest as v3_matrix_digest,
    preprocessor_digest as v3_preprocessor_digest,
    validate_feature_registry as validate_v3_feature_registry,
    structural_support_report as v3_structural_support_report,
    transform as transform_v3_membership,
    validate_authorization as validate_v3_authorization,
    validate_temporal_fold as validate_v3_temporal_fold,
)
from .rules import (
    ActionEligibilityResult,
    ConservationActionDefinition,
    DisqualificationReasonCode,
    DISQUALIFICATION_DESCRIPTIONS,
    EligibilityRulesEngine,
    EligibleActionSet,
    PolicyContext,
    evaluate_action_eligibility,
    evaluate_channel_consent,
    evaluate_contact_cooling_off,
    evaluate_grace_period,
    evaluate_legal_freeze,
    evaluate_policy_viability,
    evaluate_tenure_bounds,
    get_standard_action_catalog,
)
from .optimization import (
    ActionUtility,
    OptimalRecommendation,
    PolicyValuation,
    PortfolioAllocation,
    PortfolioOptimizer,
    SPECIALIST_ACTIONS,
    UpliftQuadrant,
    classify_uplift_quadrant,
    estimate_treatment_effect,
    evaluate_action_utilities,
    select_best_unconstrained_action,
)


__version__ = "0.1.0"

__all__ = [
    "GeneratorConfig",
    "V3CorpusConfig", "V3Corpus", "V3Features", "V3Observation", "V3OracleRecord",
    "V3_ACCEPTANCE_PROTOCOL_VERSION", "V3_ARTIFACT_VERSION",
    "V3_CANONICALIZATION_VERSION", "V3_CONTRACT_VERSION", "V3_EVENT_SCHEMA_VERSION",
    "V3_FINAL_HOLDOUT_STATUS", "V3_OBSERVATION_SCHEMA_VERSION",
    "V3_ORACLE_SIDECAR_VERSION", "V3_QUADRATURE_VERSION", "V3_RANDOM_DOMAINS",
    "V3_STREAM_REGISTRY_VERSION", "artifact_id", "canonical_json_bytes",
    "complete_configuration", "execution_id", "generate_v3_corpus",
    "intervention_manifest", "primitive_normal", "primitive_uniform",
    "reconstruct_v3_features", "scenario_configuration", "stable_identifier",
    "stream_set_id", "structural_configuration", "v3_competing_hazards",
    "v3_corpus_digest", "v3_cumulative_incidence", "v3_observable_oracle",
    "validate_feature_lineage", "validate_v3_corpus", "validate_v3_feature_payload",
    "visible_events",
    "V31_ACCEPTANCE_PROTOCOL_VERSION", "V31_SIMULATOR_CONTRACT_VERSION",
    "V31CorpusConfig", "generate_v31_corpus",
    "V4_ACCEPTANCE_PROTOCOL_VERSION", "V4_ARTIFACT_VERSION",
    "V4_COEFFICIENT_REGISTRY_VERSION", "V4_EVENT_SCHEMA_VERSION",
    "V4_OBSERVATION_SCHEMA_VERSION", "V4_ORACLE_SIDECAR_VERSION",
    "V4_QUADRATURE_VERSION", "V4_RANDOM_DOMAINS",
    "V4_SIMULATOR_CONTRACT_VERSION", "V4_STREAM_REGISTRY_VERSION",
    "V4CorpusConfig", "V4Corpus", "V4Features", "V4Observation",
    "V4OracleRecord", "generate_v4_corpus", "public_mechanism_terms",
    "reconstruct_v4_features", "v4_artifact_id", "v4_competing_hazards",
    "v4_complete_configuration", "v4_corpus_digest", "v4_cumulative_incidence",
    "v4_execution_id", "v4_observable_oracle", "v4_stream_set_id",
    "validate_v4_corpus",
    "V3_EVALUATION_FOLDS", "V3_FEATURE_DICTIONARY_VERSION",
    "V3_FEATURE_GROUPS", "V3_FEATURE_PIPELINE_VERSION",
    "V3_CANDIDATE_SELECTION_MEMBERSHIP_VERSION", "V3_CANDIDATE_VERSION",
    "V3_DIAGNOSTIC_VERSION", "V3_EVALUATION_ACCEPTANCE_PROTOCOL_VERSION",
    "V3_SCORING_AUTHORIZATION_VERSION", "V3_SPLIT_VERSION", "V3TemporalFold",
    "V3_STRUCTURAL_SUPPORT_VERSION", "V3Matrix", "V3Preprocessor",
    "V3ScoringAuthorization", "authorize_v3_scoring",
    "build_v3_selection_fold", "build_v3_temporal_folds",
    "compare_v3_candidates", "fit_v3_preprocessor", "transform_v3_membership",
    "v3_feature_diagnostics", "v3_matrix_digest", "v3_preprocessor_digest",
    "validate_v3_authorization",
    "validate_v3_feature_registry", "validate_v3_temporal_fold",
    "v3_structural_support_report",
    "V2CorpusConfig",
    "V2Corpus",
    "V2Features",
    "V2Observation",
    "V2OracleRecord",
    "V2_ARTIFACT_VERSION",
    "V2_EVENT_SCHEMA_VERSION",
    "V2_ORACLE_SIDECAR_VERSION",
    "V2_QUADRATURE_VERSION",
    "V2_NUMERIC_SERIALIZATION_DECIMALS",
    "V2_ACCEPTANCE_PROTOCOL_VERSION",
    "V2_CONFIGURATION_CANONICALIZATION_VERSION",
    "V2_FINAL_HOLDOUT_STATUS",
    "V2_LABEL_POLICY_VERSION",
    "V2_OBSERVATION_CONTRACT_VERSION",
    "V2_RANDOM_DOMAINS",
    "V2_ROLE_PROPORTIONS",
    "V2_SIMULATOR_CONTRACT_VERSION",
    "CONFIGURATION_CANONICALIZATION_VERSION",
    "CONFIGURATION_DIGEST_ALGORITHM",
    "LEGACY_GENERATOR_VERSION",
    "NAMESPACED_GENERATOR_VERSION",
    "BASELINE_RANDOM_SEED",
    "BOOSTED_MODEL_VERSION",
    "BOOSTED_RANDOM_SEED",
    "BOOSTED_TRAINING_CONFIGURATION_VERSION",
    "FROZEN_BOOSTED_SPECIFICATION",
    "FROZEN_LOGISTIC_SPECIFICATION",
    "FROZEN_DIAGNOSTIC_SPECIFICATION",
    "LOGISTIC_BASELINE_VERSION",
    "TRAINING_CONFIGURATION_VERSION",
    "FEATURE_DEFINITIONS",
    "FEATURE_DICTIONARY_VERSION",
    "FEATURE_GUARD_VERSION",
    "FEATURE_PIPELINE_VERSION",
    "FEATURE_DIAGNOSTICS_VERSION",
    "DIAGNOSTIC_CONFIGURATION_VERSION",
    "DIAGNOSTIC_RANDOM_SEED",
    "LABEL_HORIZON_DAYS",
    "LABEL_POLICY_VERSION",
    "OBSERVATION_CONTRACT_VERSION",
    "CANONICAL_TEMPORAL_SPLIT_SPECIFICATION",
    "TEMPORAL_SPLIT_CONTRACT_VERSION",
    "ObservationFeatures",
    "ObservationRecord",
    "OutcomeLabel",
    "ExtractedFeatureRow",
    "FeatureDefinition",
    "FeaturePipelineResult",
    "FittedPreprocessor",
    "ModelMatrix",
    "BaselineEvaluation",
    "BaselineMetrics",
    "FittedLogisticBaseline",
    "LogisticBaselineSpecification",
    "BoostedModelSpecification",
    "FittedBoostedModel",
    "InferenceMatrix",
    "ScoringAuthorization",
    "ScoringAuthorizations",
    "DiagnosticSpecification",
    "TemporalSplitResult",
    "TemporalSplitSpecification",
    "UNKNOWN_CATEGORY",
    "SCORING_AUTHORIZATION_VERSION",
    "HISTORICAL_TRAIN",
    "NON_FINAL_VALIDATION",
    "DIAGNOSTIC_DERIVATIVE",
    "assign_temporal_splits",
    "build_first_billing_observations",
    "build_feature_pipeline",
    "build_observation",
    "authorize_diagnostic_derivative",
    "authorize_feature_pipeline",
    "coefficient_summary",
    "compare_models",
    "diagnostic_flags",
    "evaluate_boosted_model",
    "evaluate_logistic_baseline",
    "first_billing_observation_time",
    "fit_preprocessor",
    "fit_logistic_baseline",
    "fit_boosted_model",
    "fitted_boosted_bytes",
    "fitted_baseline_bytes",
    "fitted_state_bytes",
    "identifier_and_cardinality_checks",
    "identifier_token_matches",
    "find_exact_deterministic_proxies",
    "canonical_configuration",
    "canonical_v2_configuration",
    "competing_hazards",
    "corpus_jsonl",
    "cumulative_incidence",
    "configuration_digest",
    "v2_configuration_digest",
    "v2_domain_seed",
    "v2_run_identity",
    "generate_legacy_policy_histories",
    "generate_policy_histories",
    "generate_v2_corpus",
    "generation_provenance",
    "legacy_generation_provenance",
    "run_identity",
    "verify_generation_provenance",
    "extract_feature_row",
    "feature_dictionary",
    "histories_to_jsonl",
    "PolicyState",
    "project_identity",
    "reconstruct_policy_state",
    "source_observation_digest",
    "matrix_digest",
    "inference_matrix_from_model_matrix",
    "predict_logistic_inference",
    "predict_positive_probabilities",
    "predict_boosted_inference",
    "predict_boosted_probabilities",
    "perturbation_flags",
    "shallow_feature_models",
    "source_feature_groups",
    "targeted_permutation_checks",
    "training_mutual_information",
    "summarize_observations",
    "summarize_temporal_split",
    "validate_feature_payload",
    "validate_feature_dictionary",
    "validate_observation_records",
    "validate_scoring_authorization",
    "validate_policy_history",
    "validate_temporal_split",
    "observable_oracle",
    "validate_v2_corpus",
    "validate_v2_feature_payload",
    "validate_dispositions",
    "transform_partition",
    "XGBOOST_PINNED_VERSION",
    "ActionEligibilityResult",
    "ConservationActionDefinition",
    "DisqualificationReasonCode",
    "DISQUALIFICATION_DESCRIPTIONS",
    "EligibilityRulesEngine",
    "EligibleActionSet",
    "PolicyContext",
    "evaluate_action_eligibility",
    "evaluate_channel_consent",
    "evaluate_contact_cooling_off",
    "evaluate_grace_period",
    "evaluate_legal_freeze",
    "evaluate_policy_viability",
    "evaluate_tenure_bounds",
    "get_standard_action_catalog",
    "ActionUtility",
    "OptimalRecommendation",
    "PolicyValuation",
    "PortfolioAllocation",
    "PortfolioOptimizer",
    "SPECIALIST_ACTIONS",
    "UpliftQuadrant",
    "classify_uplift_quadrant",
    "estimate_treatment_effect",
    "evaluate_action_utilities",
    "select_best_unconstrained_action",
]


def project_identity() -> dict[str, str]:
    """Return public project metadata used by the scaffold smoke test."""
    return {
        "name": "Inforsight",
        "tagline": "See Risk. Shape Action.",
        "data_policy": "synthetic-only",
    }
