"""Inforsight's clean-room fictional policy-event simulator."""

from .config import GeneratorConfig
from .generator import (
    CONFIGURATION_CANONICALIZATION_VERSION,
    CONFIGURATION_DIGEST_ALGORITHM,
    LEGACY_GENERATOR_VERSION,
    NAMESPACED_GENERATOR_VERSION,
    canonical_configuration,
    configuration_digest,
    generate_legacy_policy_histories,
    generate_policy_histories,
    generation_provenance,
    legacy_generation_provenance,
    run_identity,
    verify_generation_provenance,
)
from .features import (
    FEATURE_DEFINITIONS,
    FEATURE_DICTIONARY_VERSION,
    FEATURE_PIPELINE_VERSION,
    ExtractedFeatureRow,
    FeatureDefinition,
    extract_feature_row,
    feature_dictionary,
    validate_feature_dictionary,
)
from .leakage import (
    FEATURE_GUARD_VERSION,
    find_exact_deterministic_proxies,
    validate_feature_payload,
    validate_observation_records,
)
from .observations import (
    LABEL_HORIZON_DAYS,
    LABEL_POLICY_VERSION,
    OBSERVATION_CONTRACT_VERSION,
    ObservationFeatures,
    ObservationRecord,
    OutcomeLabel,
    build_first_billing_observations,
    build_observation,
    first_billing_observation_time,
    summarize_observations,
)
from .modeling import (
    BASELINE_RANDOM_SEED,
    FROZEN_LOGISTIC_SPECIFICATION,
    LOGISTIC_BASELINE_VERSION,
    TRAINING_CONFIGURATION_VERSION,
    BaselineEvaluation,
    BaselineMetrics,
    FittedLogisticBaseline,
    LogisticBaselineSpecification,
    coefficient_summary,
    evaluate_logistic_baseline,
    fit_logistic_baseline,
    fitted_baseline_bytes,
    predict_logistic_inference,
    predict_positive_probabilities,
)
from .boosted_modeling import (
    BOOSTED_MODEL_VERSION,
    BOOSTED_RANDOM_SEED,
    BOOSTED_TRAINING_CONFIGURATION_VERSION,
    FROZEN_BOOSTED_SPECIFICATION,
    XGBOOST_PINNED_VERSION,
    BoostedModelSpecification,
    FittedBoostedModel,
    compare_models,
    evaluate_boosted_model,
    fit_boosted_model,
    fitted_boosted_bytes,
    predict_boosted_inference,
    predict_boosted_probabilities,
)
from .diagnostics import (
    DIAGNOSTIC_CONFIGURATION_VERSION,
    DIAGNOSTIC_RANDOM_SEED,
    FEATURE_DIAGNOSTICS_VERSION,
    FROZEN_DIAGNOSTIC_SPECIFICATION,
    DiagnosticSpecification,
    diagnostic_flags,
    identifier_and_cardinality_checks,
    identifier_token_matches,
    perturbation_flags,
    shallow_feature_models,
    source_feature_groups,
    targeted_permutation_checks,
    training_mutual_information,
    validate_dispositions,
)
from .reconstruction import PolicyState, reconstruct_policy_state
from .preprocessing import (
    UNKNOWN_CATEGORY,
    FeaturePipelineResult,
    FittedPreprocessor,
    ModelMatrix,
    build_feature_pipeline,
    fit_preprocessor,
    fitted_state_bytes,
    matrix_digest,
    transform_partition,
)
from .scoring_authorization import (
    DIAGNOSTIC_DERIVATIVE,
    HISTORICAL_TRAIN,
    NON_FINAL_VALIDATION,
    SCORING_AUTHORIZATION_VERSION,
    InferenceMatrix,
    ScoringAuthorization,
    ScoringAuthorizations,
    authorize_diagnostic_derivative,
    authorize_feature_pipeline,
    inference_matrix_from_model_matrix,
    validate_scoring_authorization,
)
from .serialization import histories_to_jsonl
from .splitting import (
    CANONICAL_TEMPORAL_SPLIT_SPECIFICATION,
    TEMPORAL_SPLIT_CONTRACT_VERSION,
    TemporalSplitResult,
    TemporalSplitSpecification,
    assign_temporal_splits,
    source_observation_digest,
    summarize_temporal_split,
    validate_temporal_split,
)
from .validation import validate_policy_history
from .v2_config import (
    V2_ACCEPTANCE_PROTOCOL_VERSION,
    V2_CONFIGURATION_CANONICALIZATION_VERSION,
    V2_FINAL_HOLDOUT_STATUS,
    V2_LABEL_POLICY_VERSION,
    V2_OBSERVATION_CONTRACT_VERSION,
    V2_RANDOM_DOMAINS,
    V2_ROLE_PROPORTIONS,
    V2_SIMULATOR_CONTRACT_VERSION,
    V2CorpusConfig,
    canonical_v2_configuration,
    v2_configuration_digest,
    v2_domain_seed,
    v2_run_identity,
)
from .v2_corpus import (
    V2_ARTIFACT_VERSION,
    V2_EVENT_SCHEMA_VERSION,
    V2_ORACLE_SIDECAR_VERSION,
    V2_QUADRATURE_VERSION,
    V2_NUMERIC_SERIALIZATION_DECIMALS,
    V2Corpus,
    V2Features,
    V2Observation,
    V2OracleRecord,
    competing_hazards,
    corpus_jsonl,
    cumulative_incidence,
    generate_v2_corpus,
    observable_oracle,
    validate_v2_corpus,
    validate_v2_feature_payload,
)


__version__ = "0.1.0"

__all__ = [
    "GeneratorConfig",
    "V2CorpusConfig",
    "V2Corpus",
    "V2Features",
    "V2Observation",
    "V2OracleRecord",
    "V2_ARTIFACT_VERSION",
    "V2_EVENT_SCHEMA_VERSION",
    "V2_ORACLE_SIDECAR_VERSION",
    "V2_QUADRATURE_VERSION",
    "V2_NUMERIC_SERIALIZATION_DECIMALS",
    "V2_ACCEPTANCE_PROTOCOL_VERSION",
    "V2_CONFIGURATION_CANONICALIZATION_VERSION",
    "V2_FINAL_HOLDOUT_STATUS",
    "V2_LABEL_POLICY_VERSION",
    "V2_OBSERVATION_CONTRACT_VERSION",
    "V2_RANDOM_DOMAINS",
    "V2_ROLE_PROPORTIONS",
    "V2_SIMULATOR_CONTRACT_VERSION",
    "CONFIGURATION_CANONICALIZATION_VERSION",
    "CONFIGURATION_DIGEST_ALGORITHM",
    "LEGACY_GENERATOR_VERSION",
    "NAMESPACED_GENERATOR_VERSION",
    "BASELINE_RANDOM_SEED",
    "BOOSTED_MODEL_VERSION",
    "BOOSTED_RANDOM_SEED",
    "BOOSTED_TRAINING_CONFIGURATION_VERSION",
    "FROZEN_BOOSTED_SPECIFICATION",
    "FROZEN_LOGISTIC_SPECIFICATION",
    "FROZEN_DIAGNOSTIC_SPECIFICATION",
    "LOGISTIC_BASELINE_VERSION",
    "TRAINING_CONFIGURATION_VERSION",
    "FEATURE_DEFINITIONS",
    "FEATURE_DICTIONARY_VERSION",
    "FEATURE_GUARD_VERSION",
    "FEATURE_PIPELINE_VERSION",
    "FEATURE_DIAGNOSTICS_VERSION",
    "DIAGNOSTIC_CONFIGURATION_VERSION",
    "DIAGNOSTIC_RANDOM_SEED",
    "LABEL_HORIZON_DAYS",
    "LABEL_POLICY_VERSION",
    "OBSERVATION_CONTRACT_VERSION",
    "CANONICAL_TEMPORAL_SPLIT_SPECIFICATION",
    "TEMPORAL_SPLIT_CONTRACT_VERSION",
    "ObservationFeatures",
    "ObservationRecord",
    "OutcomeLabel",
    "ExtractedFeatureRow",
    "FeatureDefinition",
    "FeaturePipelineResult",
    "FittedPreprocessor",
    "ModelMatrix",
    "BaselineEvaluation",
    "BaselineMetrics",
    "FittedLogisticBaseline",
    "LogisticBaselineSpecification",
    "BoostedModelSpecification",
    "FittedBoostedModel",
    "InferenceMatrix",
    "ScoringAuthorization",
    "ScoringAuthorizations",
    "DiagnosticSpecification",
    "TemporalSplitResult",
    "TemporalSplitSpecification",
    "UNKNOWN_CATEGORY",
    "SCORING_AUTHORIZATION_VERSION",
    "HISTORICAL_TRAIN",
    "NON_FINAL_VALIDATION",
    "DIAGNOSTIC_DERIVATIVE",
    "assign_temporal_splits",
    "build_first_billing_observations",
    "build_feature_pipeline",
    "build_observation",
    "authorize_diagnostic_derivative",
    "authorize_feature_pipeline",
    "coefficient_summary",
    "compare_models",
    "diagnostic_flags",
    "evaluate_boosted_model",
    "evaluate_logistic_baseline",
    "first_billing_observation_time",
    "fit_preprocessor",
    "fit_logistic_baseline",
    "fit_boosted_model",
    "fitted_boosted_bytes",
    "fitted_baseline_bytes",
    "fitted_state_bytes",
    "identifier_and_cardinality_checks",
    "identifier_token_matches",
    "find_exact_deterministic_proxies",
    "canonical_configuration",
    "canonical_v2_configuration",
    "competing_hazards",
    "corpus_jsonl",
    "cumulative_incidence",
    "configuration_digest",
    "v2_configuration_digest",
    "v2_domain_seed",
    "v2_run_identity",
    "generate_legacy_policy_histories",
    "generate_policy_histories",
    "generate_v2_corpus",
    "generation_provenance",
    "legacy_generation_provenance",
    "run_identity",
    "verify_generation_provenance",
    "extract_feature_row",
    "feature_dictionary",
    "histories_to_jsonl",
    "PolicyState",
    "project_identity",
    "reconstruct_policy_state",
    "source_observation_digest",
    "matrix_digest",
    "inference_matrix_from_model_matrix",
    "predict_logistic_inference",
    "predict_positive_probabilities",
    "predict_boosted_inference",
    "predict_boosted_probabilities",
    "perturbation_flags",
    "shallow_feature_models",
    "source_feature_groups",
    "targeted_permutation_checks",
    "training_mutual_information",
    "summarize_observations",
    "summarize_temporal_split",
    "validate_feature_payload",
    "validate_feature_dictionary",
    "validate_observation_records",
    "validate_scoring_authorization",
    "validate_policy_history",
    "validate_temporal_split",
    "observable_oracle",
    "validate_v2_corpus",
    "validate_v2_feature_payload",
    "validate_dispositions",
    "transform_partition",
    "XGBOOST_PINNED_VERSION",
]


def project_identity() -> dict[str, str]:
    """Return public project metadata used by the scaffold smoke test."""
    return {
        "name": "Inforsight",
        "tagline": "See Risk. Shape Action.",
        "data_policy": "synthetic-only",
    }
