"""Domain models for Phase 3.03 cost-utility and uplift optimization.

Under ADR 0002, recommendations generated by this module are non-autonomous
advisory inputs for human caseworkers and maintain authorized_to_act=False.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Mapping


class UpliftQuadrant(str, Enum):
    """Canonical customer treatment responsiveness quadrants."""

    PERSUADABLE = "PERSUADABLE"  # High risk, high uplift -> prioritize for outreach
    LOST_CAUSE = "LOST_CAUSE"    # High risk, near-zero uplift -> divert from expensive casework
    SURE_THING = "SURE_THING"    # Low risk, minimal uplift -> avoid unnecessary touch
    SLEEPING_DOG = "SLEEPING_DOG" # Outreach triggers adverse lapse -> strict abstention


@dataclass(frozen=True)
class PolicyValuation:
    """Financial valuation parameters for a policy."""

    policy_id: str
    annual_premium_usd: float
    customer_lifetime_value_usd: float

    def __post_init__(self) -> None:
        if not self.policy_id:
            raise ValueError("policy_id cannot be empty")
        if self.annual_premium_usd < 0:
            raise ValueError("annual_premium_usd cannot be negative")
        if self.customer_lifetime_value_usd < 0:
            raise ValueError("customer_lifetime_value_usd cannot be negative")


@dataclass(frozen=True)
class ActionUtility:
    """Expected economic utility and uplift metrics for a candidate action."""

    action_type: str
    is_eligible: bool
    treatment_effect: float  # Tau_a(X) = P(lapse|control) - P(lapse|action)
    gross_benefit_usd: float # Tau_a * V_policy
    direct_cost_usd: float   # c(a)
    net_utility_usd: float   # Gross benefit - direct cost
    uplift_quadrant: UpliftQuadrant

    def to_dict(self) -> dict[str, Any]:
        return {
            "action_type": self.action_type,
            "is_eligible": self.is_eligible,
            "treatment_effect": round(self.treatment_effect, 4),
            "gross_benefit_usd": round(self.gross_benefit_usd, 2),
            "direct_cost_usd": round(self.direct_cost_usd, 2),
            "net_utility_usd": round(self.net_utility_usd, 2),
            "uplift_quadrant": self.uplift_quadrant.value,
        }


@dataclass(frozen=True)
class OptimalRecommendation:
    """Optimal conservation recommendation for an individual policy."""

    policy_id: str
    recommended_action: str
    expected_net_utility_usd: float
    uplift_quadrant: UpliftQuadrant
    rank_score: float
    action_utilities: dict[str, ActionUtility]
    authorized_to_act: bool = False  # Strict ADR 0002 boundary

    def __post_init__(self) -> None:
        if self.authorized_to_act is not False:
            raise ValueError("ADR 0002 Violation: authorized_to_act must be False")

    def to_dict(self) -> dict[str, Any]:
        return {
            "policy_id": self.policy_id,
            "recommended_action": self.recommended_action,
            "expected_net_utility_usd": round(self.expected_net_utility_usd, 2),
            "uplift_quadrant": self.uplift_quadrant.value,
            "rank_score": round(self.rank_score, 4),
            "authorized_to_act": self.authorized_to_act,
            "action_utilities": {
                k: v.to_dict() for k, v in sorted(self.action_utilities.items())
            },
        }


@dataclass(frozen=True)
class PortfolioAllocation:
    """Portfolio-level triage allocation under capacity and budget constraints."""

    as_of: datetime
    specialist_capacity: int
    allocated_specialist_count: int
    total_budget_usd: float
    allocated_cost_usd: float
    net_portfolio_value_usd: float
    recommendations: tuple[OptimalRecommendation, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "as_of": self.as_of.isoformat().replace("+00:00", "Z"),
            "specialist_capacity": self.specialist_capacity,
            "allocated_specialist_count": self.allocated_specialist_count,
            "total_budget_usd": round(self.total_budget_usd, 2),
            "allocated_cost_usd": round(self.allocated_cost_usd, 2),
            "net_portfolio_value_usd": round(self.net_portfolio_value_usd, 2),
            "recommendations": [rec.to_dict() for rec in self.recommendations],
        }
