"""Domain models for Phase 3.03 cost-utility and uplift optimization.

Under ADR 0002, recommendations generated by this module are non-autonomous
advisory inputs for human caseworkers and maintain authorized_to_act=False.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Mapping

from inforsight_simulator.economics import (
    ECONOMICS_CONTRACT_VERSION,
    EFFECT_ID,
    VALUE_METRIC_ID,
)


class UpliftQuadrant(str, Enum):
    """Canonical customer treatment responsiveness quadrants."""

    PERSUADABLE = "PERSUADABLE"  # High risk, high uplift -> prioritize for outreach
    LOST_CAUSE = "LOST_CAUSE"    # High risk, near-zero uplift -> divert from expensive casework
    SURE_THING = "SURE_THING"    # Low risk, minimal uplift -> avoid unnecessary touch
    SLEEPING_DOG = "SLEEPING_DOG" # Outreach triggers adverse lapse -> strict abstention


@dataclass(frozen=True)
class PolicyValuation:
    """Policy value basis; CLV is retained only for legacy input compatibility."""

    policy_id: str
    annual_premium_usd: float
    customer_lifetime_value_usd: float
    snapshot_id: str = "legacy-unbound-snapshot"
    snapshot_version: str = "1.0.0"
    catalog_sha256: str = "legacy-unbound-catalog"

    def __post_init__(self) -> None:
        if not self.policy_id:
            raise ValueError("policy_id cannot be empty")
        if self.annual_premium_usd < 0:
            raise ValueError("annual_premium_usd cannot be negative")
        if self.customer_lifetime_value_usd < 0:
            raise ValueError("customer_lifetime_value_usd cannot be negative")


@dataclass(frozen=True)
class ActionUtility:
    """Contract-bound modeled annual-premium-preserved value for an action."""

    action_type: str
    is_eligible: bool
    treatment_effect: float  # P(combined termination|control) - P(...|action)
    gross_benefit_usd: float # Tau_a * V_policy
    direct_cost_usd: float   # c(a)
    net_utility_usd: float   # Gross benefit - direct cost
    uplift_quadrant: UpliftQuadrant
    action_id: str = ""
    effect_id: str = EFFECT_ID
    economics_contract_version: str = ECONOMICS_CONTRACT_VERSION
    metric_id: str = VALUE_METRIC_ID
    gross_expected_value_usd_micros: int = 0
    direct_cost_usd_micros: int = 0
    net_expected_value_usd_micros: int = 0
    personnel_seconds: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "action_type": self.action_type,
            "is_eligible": self.is_eligible,
            "treatment_effect": round(self.treatment_effect, 4),
            "gross_benefit_usd": round(self.gross_benefit_usd, 2),
            "direct_cost_usd": round(self.direct_cost_usd, 2),
            "net_utility_usd": round(self.net_utility_usd, 2),
            "uplift_quadrant": self.uplift_quadrant.value,
            "action_id": self.action_id,
            "effect_id": self.effect_id,
            "economics_contract_version": self.economics_contract_version,
            "metric_id": self.metric_id,
            "gross_expected_value_usd_micros": self.gross_expected_value_usd_micros,
            "direct_cost_usd_micros": self.direct_cost_usd_micros,
            "net_expected_value_usd_micros": self.net_expected_value_usd_micros,
            "personnel_seconds": self.personnel_seconds,
        }


@dataclass(frozen=True)
class OptimalRecommendation:
    """Optimal conservation recommendation for an individual policy."""

    policy_id: str
    recommended_action: str
    expected_net_utility_usd: float
    uplift_quadrant: UpliftQuadrant
    rank_score: float
    action_utilities: dict[str, ActionUtility]
    authorized_to_act: bool = False  # Strict ADR 0002 boundary
    economics_contract_version: str = ECONOMICS_CONTRACT_VERSION
    metric_id: str = VALUE_METRIC_ID

    def __post_init__(self) -> None:
        if self.authorized_to_act is not False:
            raise ValueError("ADR 0002 Violation: authorized_to_act must be False")

    @property
    def expected_net_value_usd_micros(self) -> int:
        selected = self.action_utilities.get(self.recommended_action)
        return selected.net_expected_value_usd_micros if selected is not None else 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "policy_id": self.policy_id,
            "recommended_action": self.recommended_action,
            "expected_net_utility_usd": round(self.expected_net_utility_usd, 2),
            "uplift_quadrant": self.uplift_quadrant.value,
            "rank_score": round(self.rank_score, 4),
            "authorized_to_act": self.authorized_to_act,
            "economics_contract_version": self.economics_contract_version,
            "metric_id": self.metric_id,
            "expected_net_value_usd_micros": self.expected_net_value_usd_micros,
            "action_utilities": {
                k: v.to_dict() for k, v in sorted(self.action_utilities.items())
            },
        }


@dataclass(frozen=True)
class PortfolioAllocation:
    """Portfolio-level triage allocation under capacity and budget constraints."""

    as_of: datetime
    specialist_capacity: int
    allocated_specialist_count: int
    total_budget_usd: float
    allocated_cost_usd: float
    net_portfolio_value_usd: float
    recommendations: tuple[OptimalRecommendation, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "as_of": self.as_of.isoformat().replace("+00:00", "Z"),
            "specialist_capacity": self.specialist_capacity,
            "allocated_specialist_count": self.allocated_specialist_count,
            "total_budget_usd": round(self.total_budget_usd, 2),
            "allocated_cost_usd": round(self.allocated_cost_usd, 2),
            "net_portfolio_value_usd": round(self.net_portfolio_value_usd, 2),
            "recommendations": [rec.to_dict() for rec in self.recommendations],
        }
