"""Domain models for Phase 3.03 cost-utility and uplift optimization.

Under ADR 0002, recommendations generated by this module are non-autonomous
advisory inputs for human caseworkers and maintain authorized_to_act=False.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Mapping

from inforsight_simulator.economics import (
    ECONOMICS_CONTRACT_VERSION,
    EFFECT_ID,
    VALUE_METRIC_ID,
)


class UpliftQuadrant(str, Enum):
    """Canonical customer treatment responsiveness quadrants."""

    PERSUADABLE = "PERSUADABLE"  # High risk, high uplift -> prioritize for outreach
    LOST_CAUSE = "LOST_CAUSE"    # High risk, near-zero uplift -> divert from expensive casework
    SURE_THING = "SURE_THING"    # Low risk, minimal uplift -> avoid unnecessary touch
    SLEEPING_DOG = "SLEEPING_DOG" # Outreach triggers adverse lapse -> strict abstention


@dataclass(frozen=True)
class PolicyValuation:
    """Policy value basis; CLV is retained only for legacy input compatibility."""

    policy_id: str
    annual_premium_usd: float
    customer_lifetime_value_usd: float
    snapshot_id: str = "legacy-unbound-snapshot"
    snapshot_version: str = "1.0.0"
    catalog_sha256: str = "legacy-unbound-catalog"

    def __post_init__(self) -> None:
        if not self.policy_id:
            raise ValueError("policy_id cannot be empty")
        if self.annual_premium_usd < 0:
            raise ValueError("annual_premium_usd cannot be negative")
        if self.customer_lifetime_value_usd < 0:
            raise ValueError("customer_lifetime_value_usd cannot be negative")


@dataclass(frozen=True)
class ActionUtility:
    """Contract-bound modeled annual-premium-preserved value for an action."""

    action_type: str
    is_eligible: bool
    treatment_effect: float  # P(combined termination|control) - P(...|action)
    gross_benefit_usd: float # Tau_a * V_policy
    direct_cost_usd: float   # c(a)
    net_utility_usd: float   # Gross benefit - direct cost
    uplift_quadrant: UpliftQuadrant
    action_id: str = ""
    effect_id: str = EFFECT_ID
    economics_contract_version: str = ECONOMICS_CONTRACT_VERSION
    metric_id: str = VALUE_METRIC_ID
    gross_expected_value_usd_micros: int = 0
    direct_cost_usd_micros: int = 0
    net_expected_value_usd_micros: int = 0
    personnel_seconds: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "action_type": self.action_type,
            "is_eligible": self.is_eligible,
            "treatment_effect": round(self.treatment_effect, 4),
            "gross_benefit_usd": round(self.gross_benefit_usd, 2),
            "direct_cost_usd": round(self.direct_cost_usd, 2),
            "net_utility_usd": round(self.net_utility_usd, 2),
            "uplift_quadrant": self.uplift_quadrant.value,
            "action_id": self.action_id,
            "effect_id": self.effect_id,
            "economics_contract_version": self.economics_contract_version,
            "metric_id": self.metric_id,
            "gross_expected_value_usd_micros": self.gross_expected_value_usd_micros,
            "direct_cost_usd_micros": self.direct_cost_usd_micros,
            "net_expected_value_usd_micros": self.net_expected_value_usd_micros,
            "personnel_seconds": self.personnel_seconds,
        }


@dataclass(frozen=True)
class OptimalRecommendation:
    """Optimal conservation recommendation for an individual policy."""

    policy_id: str
    recommended_action: str
    expected_net_utility_usd: float
    uplift_quadrant: UpliftQuadrant
    rank_score: float
    action_utilities: dict[str, ActionUtility]
    authorized_to_act: bool = False  # Strict ADR 0002 boundary
    economics_contract_version: str = ECONOMICS_CONTRACT_VERSION
    metric_id: str = VALUE_METRIC_ID

    def __post_init__(self) -> None:
        if self.authorized_to_act is not False:
            raise ValueError("ADR 0002 Violation: authorized_to_act must be False")

    @property
    def expected_net_value_usd_micros(self) -> int:
        selected = self.action_utilities.get(self.recommended_action)
        return selected.net_expected_value_usd_micros if selected is not None else 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "policy_id": self.policy_id,
            "recommended_action": self.recommended_action,
            "expected_net_utility_usd": round(self.expected_net_utility_usd, 2),
            "uplift_quadrant": self.uplift_quadrant.value,
            "rank_score": round(self.rank_score, 4),
            "authorized_to_act": self.authorized_to_act,
            "economics_contract_version": self.economics_contract_version,
            "metric_id": self.metric_id,
            "expected_net_value_usd_micros": self.expected_net_value_usd_micros,
            "action_utilities": {
                k: v.to_dict() for k, v in sorted(self.action_utilities.items())
            },
        }


@dataclass(frozen=True)
class PortfolioAllocation:
    """Contract-bound portfolio allocation using exact RH-04 resource units."""

    allocation_id: str
    portfolio_id: str
    as_of: datetime
    budget_capacity_usd_micros: int
    budget_used_usd_micros: int
    personnel_capacity_seconds: int
    personnel_used_seconds: int
    objective_usd_micros: int
    recommendations: tuple[OptimalRecommendation, ...]
    occurrence_ids: tuple[str, ...]
    allocator_id: str = "inforsight.portfolio-allocation"
    allocator_version: str = "1.0.0"
    status: str = "AVAILABLE"
    failure_code: str | None = None

    def __post_init__(self) -> None:
        for name in (
            "budget_capacity_usd_micros",
            "budget_used_usd_micros",
            "personnel_capacity_seconds",
            "personnel_used_seconds",
        ):
            if getattr(self, name) < 0:
                raise ValueError(f"INVALID_CAPACITY: {name} cannot be negative")
        if self.budget_used_usd_micros > self.budget_capacity_usd_micros:
            raise ValueError("INFEASIBLE_SELECTION: budget capacity exceeded")
        if self.personnel_used_seconds > self.personnel_capacity_seconds:
            raise ValueError("INFEASIBLE_SELECTION: personnel capacity exceeded")
        if len(self.recommendations) != len(self.occurrence_ids):
            raise ValueError("CONTEXT_MISMATCH: occurrence and recommendation counts differ")

    @property
    def total_budget_usd(self) -> float:
        return self.budget_capacity_usd_micros / 1_000_000

    @property
    def allocated_cost_usd(self) -> float:
        return self.budget_used_usd_micros / 1_000_000

    @property
    def net_portfolio_value_usd(self) -> float:
        return self.objective_usd_micros / 1_000_000

    @property
    def specialist_capacity(self) -> int:
        """Legacy display-only whole-hour equivalent; not a governed resource."""
        return self.personnel_capacity_seconds // 3_600

    @property
    def allocated_specialist_count(self) -> int:
        """Legacy compatibility count for historical callers."""
        return sum(
            rec.recommended_action
            in {"specialist_phone_outreach", "grace_period_consultation"}
            for rec in self.recommendations
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "allocator_id": self.allocator_id,
            "allocator_version": self.allocator_version,
            "allocation_id": self.allocation_id,
            "portfolio_id": self.portfolio_id,
            "as_of": self.as_of.isoformat().replace("+00:00", "Z"),
            "status": self.status,
            "failure_code": self.failure_code,
            "budget_capacity_usd_micros": self.budget_capacity_usd_micros,
            "budget_used_usd_micros": self.budget_used_usd_micros,
            "budget_available_usd_micros": self.budget_capacity_usd_micros - self.budget_used_usd_micros,
            "budget_overflow_usd_micros": 0,
            "personnel_capacity_seconds": self.personnel_capacity_seconds,
            "personnel_used_seconds": self.personnel_used_seconds,
            "personnel_available_seconds": self.personnel_capacity_seconds - self.personnel_used_seconds,
            "personnel_overflow_seconds": 0,
            "objective_usd_micros": self.objective_usd_micros,
            "selections": [
                {
                    "occurrence_id": occurrence_id,
                    "policy_id": rec.policy_id,
                    "selected_action_id": rec.recommended_action,
                    "objective_usd_micros": rec.expected_net_value_usd_micros,
                    "direct_cost_usd_micros": rec.action_utilities[rec.recommended_action].direct_cost_usd_micros,
                    "personnel_seconds": rec.action_utilities[rec.recommended_action].personnel_seconds,
                    "authorized_to_act": False,
                }
                for occurrence_id, rec in zip(self.occurrence_ids, self.recommendations)
            ],
            "recommendations": [rec.to_dict() for rec in self.recommendations],
        }
